# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  biz-ud-mincho = {
    pname = "biz-ud-mincho";
    version = "v1.06";
    src = fetchurl {
      url = "https://github.com/googlefonts/morisawa-biz-ud-mincho/releases/download/v1.06/morisawa-biz-ud-mincho-fonts.zip";
      sha256 = "sha256-fJNjCjud61g8eCyTDfLj9Hj/uZY/RnttgEGHry6FMUk=";
    };
  };
  ddc-filter-converter_kind_labels = {
    pname = "ddc-filter-converter_kind_labels";
    version = "e143084d4a9e30f75fad3605097fda31c0650f0f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-converter_kind_labels";
      rev = "e143084d4a9e30f75fad3605097fda31c0650f0f";
      fetchSubmodules = false;
      sha256 = "sha256-Lcxl25xsfrUWXJkQIUgO2Vzst07VxrpC6jwUwhPY218=";
    };
    date = "2025-09-07";
  };
  ddc-filter-matcher_prefix = {
    pname = "ddc-filter-matcher_prefix";
    version = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-matcher_prefix";
      rev = "76c5b1f0eec7263ad56bc40e4811a88faf1a3874";
      fetchSubmodules = false;
      sha256 = "sha256-l2lHrFI1A5P4p+xno3dgme9kF7KeDU1kdBlrNOakraU=";
    };
    date = "2025-09-02";
  };
  ddc-filter-sorter_lsp_kind = {
    pname = "ddc-filter-sorter_lsp_kind";
    version = "2d082e521f6e0f8d452ad737145315606eaec532";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_lsp_kind";
      rev = "2d082e521f6e0f8d452ad737145315606eaec532";
      fetchSubmodules = false;
      sha256 = "sha256-ejTiozAzDdDi68KujdiUgaTZtuHnseqd+IhTzchK5Mw=";
    };
    date = "2025-09-08";
  };
  ddc-source-lsp-setup = {
    pname = "ddc-source-lsp-setup";
    version = "88cf5ee67d469c61788762ba407e753e18d3fc02";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddc-source-lsp-setup";
      rev = "88cf5ee67d469c61788762ba407e753e18d3fc02";
      fetchSubmodules = false;
      sha256 = "sha256-KZMZO7Tv+dIzCxIXnKsJgtz+VM2vzfq04GOMJJIu1ks=";
    };
    date = "2025-07-08";
  };
  denops-popup-preview-vim = {
    pname = "denops-popup-preview-vim";
    version = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-popup-preview.vim";
      rev = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
      fetchSubmodules = false;
      sha256 = "sha256-L3Gr+BfszlFHvmxA8M8+jJ73akQzetkX/RoLVsEB4hE=";
    };
    date = "2025-08-11";
  };
  finale-maestro = {
    pname = "finale-maestro";
    version = "cc0e26e6ae93eadca8a903a961fb5f75a8173528";
    src = fetchFromGitHub {
      owner = "eNote-GmbH";
      repo = "Maestro";
      rev = "cc0e26e6ae93eadca8a903a961fb5f75a8173528";
      fetchSubmodules = false;
      sha256 = "sha256-qyh4aUBs9NJPAoqLEgV6QclHZOlWjHzFywav0Uw4aGg=";
    };
    date = "2024-08-27";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "d593d7952e271ba67795cb556871f459aa5da0f9";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "d593d7952e271ba67795cb556871f459aa5da0f9";
      fetchSubmodules = false;
      sha256 = "sha256-HAC0xX9OCJI6xfgOsS8ntUv5N+0Hc8Q2AtHUx7ZmRjw=";
    };
    date = "2026-03-22";
  };
  skkeleton_indicator-nvim = {
    pname = "skkeleton_indicator-nvim";
    version = "bf697ad1e9798eac098ce2687da1b5a994710a31";
    src = fetchFromGitHub {
      owner = "N-yam-my";
      repo = "skkeleton_indicator.nvim";
      rev = "bf697ad1e9798eac098ce2687da1b5a994710a31";
      fetchSubmodules = false;
      sha256 = "sha256-bQ/LCwXnYxrAqHfYpEY2qNslD3znklWp4HaTGRyFE3M=";
    };
    date = "2026-01-09";
  };
  vim-sonictemplate = {
    pname = "vim-sonictemplate";
    version = "4b824ea7564c5b3700527a0751477d92d90b1bef";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "vim-sonictemplate";
      rev = "4b824ea7564c5b3700527a0751477d92d90b1bef";
      fetchSubmodules = false;
      sha256 = "sha256-YqGnPljArSwPiZ0deEnoA1APpVbevKecUKE2QDz8t+g=";
    };
    date = "2026-03-20";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "62b33658226bece18f86cd6a28e7dd57a3e65bcd";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "62b33658226bece18f86cd6a28e7dd57a3e65bcd";
      fetchSubmodules = false;
      sha256 = "sha256-MFav9vtBw6i2R/6GG/Wa0S2hSApdjIToyQC9wePIjlM=";
    };
    date = "2026-03-22";
  };
}
