# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ddc-filter-converter_kind_labels = {
    pname = "ddc-filter-converter_kind_labels";
    version = "e143084d4a9e30f75fad3605097fda31c0650f0f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-converter_kind_labels";
      rev = "e143084d4a9e30f75fad3605097fda31c0650f0f";
      fetchSubmodules = false;
      sha256 = "sha256-Lcxl25xsfrUWXJkQIUgO2Vzst07VxrpC6jwUwhPY218=";
    };
    date = "2025-09-07";
  };
  ddc-filter-sorter_lsp_kind = {
    pname = "ddc-filter-sorter_lsp_kind";
    version = "2d082e521f6e0f8d452ad737145315606eaec532";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-filter-sorter_lsp_kind";
      rev = "2d082e521f6e0f8d452ad737145315606eaec532";
      fetchSubmodules = false;
      sha256 = "sha256-ejTiozAzDdDi68KujdiUgaTZtuHnseqd+IhTzchK5Mw=";
    };
    date = "2025-09-08";
  };
  ddc-source-lsp-setup = {
    pname = "ddc-source-lsp-setup";
    version = "88cf5ee67d469c61788762ba407e753e18d3fc02";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddc-source-lsp-setup";
      rev = "88cf5ee67d469c61788762ba407e753e18d3fc02";
      fetchSubmodules = false;
      sha256 = "sha256-KZMZO7Tv+dIzCxIXnKsJgtz+VM2vzfq04GOMJJIu1ks=";
    };
    date = "2025-07-08";
  };
  denops-popup-preview-vim = {
    pname = "denops-popup-preview-vim";
    version = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "denops-popup-preview.vim";
      rev = "6ba396dfb6321b2d5a0f6782823d6e588089e596";
      fetchSubmodules = false;
      sha256 = "sha256-L3Gr+BfszlFHvmxA8M8+jJ73akQzetkX/RoLVsEB4hE=";
    };
    date = "2025-08-11";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "158ae753bc5099ab12537c23152926c42b1f7c3a";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "158ae753bc5099ab12537c23152926c42b1f7c3a";
      fetchSubmodules = false;
      sha256 = "sha256-Ee55oGlNCoKwvDxaJyRCjqY89+DU2bP+7t8o/kkh8lU=";
    };
    date = "2026-01-04";
  };
  skkeleton_indicator-nvim = {
    pname = "skkeleton_indicator-nvim";
    version = "bf697ad1e9798eac098ce2687da1b5a994710a31";
    src = fetchFromGitHub {
      owner = "N-yam-my";
      repo = "skkeleton_indicator.nvim";
      rev = "bf697ad1e9798eac098ce2687da1b5a994710a31";
      fetchSubmodules = false;
      sha256 = "sha256-bQ/LCwXnYxrAqHfYpEY2qNslD3znklWp4HaTGRyFE3M=";
    };
    date = "2026-01-09";
  };
  vim-sonictemplate = {
    pname = "vim-sonictemplate";
    version = "e4b040b67e46f591efe35fbd2a3be8d2a792f47f";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "vim-sonictemplate";
      rev = "e4b040b67e46f591efe35fbd2a3be8d2a792f47f";
      fetchSubmodules = false;
      sha256 = "sha256-PvDcQilZ7X3rQW3Ui7A/k7ruI8r6+mPEvciP+XMkid0=";
    };
    date = "2025-07-02";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "103fbb394c8f72169cf22752e06caf3c9eed0684";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "103fbb394c8f72169cf22752e06caf3c9eed0684";
      fetchSubmodules = false;
      sha256 = "sha256-RgsCZU0YxUdTfpc/Zh21xQlEy/kd1gotXRMzrvDNp7Q=";
    };
    date = "2026-01-09";
  };
}
