# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  skkeleton = {
    pname = "skkeleton";
    version = "158ae753bc5099ab12537c23152926c42b1f7c3a";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "158ae753bc5099ab12537c23152926c42b1f7c3a";
      fetchSubmodules = false;
      sha256 = "sha256-Ee55oGlNCoKwvDxaJyRCjqY89+DU2bP+7t8o/kkh8lU=";
    };
    date = "2026-01-04";
  };
  skkeleton_indicator = {
    pname = "skkeleton_indicator";
    version = "f08532787cf842b996c8a5065be7e85cd3376c1f";
    src = fetchFromGitHub {
      owner = "delphinus";
      repo = "skkeleton_indicator.nvim";
      rev = "f08532787cf842b996c8a5065be7e85cd3376c1f";
      fetchSubmodules = false;
      sha256 = "sha256-6pQdj7EcPZ5/F34Y6SERRxcgKO6KLVH/94Th78ucn2Y=";
    };
    date = "2025-04-30";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "331bf689cc51aeb4a933ecbb4105ec34cb2499e1";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "331bf689cc51aeb4a933ecbb4105ec34cb2499e1";
      fetchSubmodules = false;
      sha256 = "sha256-lRDeJXC5mqxXHQ3uBvK9ZwElyTyfROFjrjPPjFZksjg=";
    };
    date = "2026-01-06";
  };
}
